apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      labels:
        app: backend-pod
    spec:
      containers:
      - name: backend-container
        image: ghcr.io/umbertocicciaa/hello-k8s/backend:main@sha256:dc6ef54d674ff9a2dc912280a0cb9bf980bf0e122991c01449f9bf9338347514
        ports:
        - containerPort: 5001
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
      imagePullSecrets:
      - name: ghcr-secret