apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  containers:
  - name: backend-container
    image: ghcr.io/umbertocicciaa/hello-k8s/backend:main@sha256:ca17aa6443a118c30dbfdd5850f8e4f98d31fbc22314ba4b8f312eca15881c0f
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: ghcr-secret