apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
spec:
  containers:
  - name: frontend-container
    image: ghcr.io/umbertocicciaa/hello-k8s/frontend:main@sha256:710280c5786c3bf4c957d0c72da619aeb88f0f7f52ca779e58a574a2deef0707
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: ghcr-secret